spring.application.name=fitness-monolith
spring.datasource.url=jdbc:mysql://localhost:3306/fitnessdb
spring.datasource.username=root
spring.datasource.password=Iqbalazam@227966
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=f8a9c3b7d6e2f1a4c9b8e7d5f3a1c6b2e9d4f7a8c1b3d5e6f9a2c4b7e8d1f3a6